title: Zhang Bo's Blog
iconURL: assets/profile_photo.png

# for a clean URL
permalink: :slug

social:
  github: zhangbopd

plugins:
 - jekyll-feed
 - jekyll-seo-tag

### comments & analytics
hyvor_talk_website_id: 8550
google_analytics: UA-NNNNNNNN-N